# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ProgramaMatricesWXFQhS.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QTabWidget, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(728, 674)
        Dialog.setStyleSheet(u"background-color: #306998")
        self.tabWidget = QTabWidget(Dialog)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 170, 711, 491))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.txt_A00 = QLineEdit(self.tab)
        self.txt_A00.setObjectName(u"txt_A00")
        self.txt_A00.setGeometry(QRect(80, 180, 51, 21))
        self.txt_A00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.btn_Limpiar = QPushButton(self.tab)
        self.btn_Limpiar.setObjectName(u"btn_Limpiar")
        self.btn_Limpiar.setGeometry(QRect(610, 420, 91, 41))
        self.btn_Limpiar.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(140, 130, 81, 31))
        font = QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_5.setFont(font)
        self.txt_A01 = QLineEdit(self.tab)
        self.txt_A01.setObjectName(u"txt_A01")
        self.txt_A01.setGeometry(QRect(150, 180, 51, 21))
        self.txt_A01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_A02 = QLineEdit(self.tab)
        self.txt_A02.setObjectName(u"txt_A02")
        self.txt_A02.setGeometry(QRect(220, 180, 51, 21))
        self.txt_A02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_A12 = QLineEdit(self.tab)
        self.txt_A12.setObjectName(u"txt_A12")
        self.txt_A12.setGeometry(QRect(220, 210, 51, 21))
        self.txt_A12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_A11 = QLineEdit(self.tab)
        self.txt_A11.setObjectName(u"txt_A11")
        self.txt_A11.setGeometry(QRect(150, 210, 51, 21))
        self.txt_A11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_A10 = QLineEdit(self.tab)
        self.txt_A10.setObjectName(u"txt_A10")
        self.txt_A10.setGeometry(QRect(80, 210, 51, 21))
        self.txt_A10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_A22 = QLineEdit(self.tab)
        self.txt_A22.setObjectName(u"txt_A22")
        self.txt_A22.setGeometry(QRect(220, 240, 51, 21))
        self.txt_A22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_A21 = QLineEdit(self.tab)
        self.txt_A21.setObjectName(u"txt_A21")
        self.txt_A21.setGeometry(QRect(150, 240, 51, 21))
        self.txt_A21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_A20 = QLineEdit(self.tab)
        self.txt_A20.setObjectName(u"txt_A20")
        self.txt_A20.setGeometry(QRect(80, 240, 51, 21))
        self.txt_A20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_B22 = QLineEdit(self.tab)
        self.txt_B22.setObjectName(u"txt_B22")
        self.txt_B22.setGeometry(QRect(580, 240, 51, 21))
        self.txt_B22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_B20 = QLineEdit(self.tab)
        self.txt_B20.setObjectName(u"txt_B20")
        self.txt_B20.setGeometry(QRect(440, 240, 51, 21))
        self.txt_B20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_B12 = QLineEdit(self.tab)
        self.txt_B12.setObjectName(u"txt_B12")
        self.txt_B12.setGeometry(QRect(580, 210, 51, 21))
        self.txt_B12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_6 = QLabel(self.tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(500, 130, 81, 31))
        self.label_6.setFont(font)
        self.txt_B02 = QLineEdit(self.tab)
        self.txt_B02.setObjectName(u"txt_B02")
        self.txt_B02.setGeometry(QRect(580, 180, 51, 21))
        self.txt_B02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_B01 = QLineEdit(self.tab)
        self.txt_B01.setObjectName(u"txt_B01")
        self.txt_B01.setGeometry(QRect(510, 180, 51, 21))
        self.txt_B01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_B10 = QLineEdit(self.tab)
        self.txt_B10.setObjectName(u"txt_B10")
        self.txt_B10.setGeometry(QRect(440, 210, 51, 21))
        self.txt_B10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_B21 = QLineEdit(self.tab)
        self.txt_B21.setObjectName(u"txt_B21")
        self.txt_B21.setGeometry(QRect(510, 240, 51, 21))
        self.txt_B21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_B00 = QLineEdit(self.tab)
        self.txt_B00.setObjectName(u"txt_B00")
        self.txt_B00.setGeometry(QRect(440, 180, 51, 21))
        self.txt_B00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_B11 = QLineEdit(self.tab)
        self.txt_B11.setObjectName(u"txt_B11")
        self.txt_B11.setGeometry(QRect(510, 210, 51, 21))
        self.txt_B11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_7 = QLabel(self.tab)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(320, 290, 81, 31))
        self.label_7.setFont(font)
        self.lbl_AB00 = QLabel(self.tab)
        self.lbl_AB00.setObjectName(u"lbl_AB00")
        self.lbl_AB00.setGeometry(QRect(260, 330, 61, 16))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.lbl_AB00.setFont(font1)
        self.lbl_AB01 = QLabel(self.tab)
        self.lbl_AB01.setObjectName(u"lbl_AB01")
        self.lbl_AB01.setGeometry(QRect(330, 330, 61, 16))
        self.lbl_AB01.setFont(font1)
        self.lbl_AB02 = QLabel(self.tab)
        self.lbl_AB02.setObjectName(u"lbl_AB02")
        self.lbl_AB02.setGeometry(QRect(400, 330, 61, 16))
        self.lbl_AB02.setFont(font1)
        self.lbl_AB10 = QLabel(self.tab)
        self.lbl_AB10.setObjectName(u"lbl_AB10")
        self.lbl_AB10.setGeometry(QRect(260, 360, 61, 16))
        self.lbl_AB10.setFont(font1)
        self.lbl_AB11 = QLabel(self.tab)
        self.lbl_AB11.setObjectName(u"lbl_AB11")
        self.lbl_AB11.setGeometry(QRect(330, 360, 61, 16))
        self.lbl_AB11.setFont(font1)
        self.lbl_AB12 = QLabel(self.tab)
        self.lbl_AB12.setObjectName(u"lbl_AB12")
        self.lbl_AB12.setGeometry(QRect(400, 360, 61, 16))
        self.lbl_AB12.setFont(font1)
        self.lbl_AB20 = QLabel(self.tab)
        self.lbl_AB20.setObjectName(u"lbl_AB20")
        self.lbl_AB20.setGeometry(QRect(260, 390, 61, 16))
        self.lbl_AB20.setFont(font1)
        self.lbl_AB21 = QLabel(self.tab)
        self.lbl_AB21.setObjectName(u"lbl_AB21")
        self.lbl_AB21.setGeometry(QRect(330, 390, 61, 16))
        self.lbl_AB21.setFont(font1)
        self.lbl_AB22 = QLabel(self.tab)
        self.lbl_AB22.setObjectName(u"lbl_AB22")
        self.lbl_AB22.setGeometry(QRect(400, 390, 61, 16))
        self.lbl_AB22.setFont(font1)
        self.btn_Sumar = QPushButton(self.tab)
        self.btn_Sumar.setObjectName(u"btn_Sumar")
        self.btn_Sumar.setGeometry(QRect(510, 420, 91, 41))
        self.btn_Sumar.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_8 = QLabel(self.tab)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 20, 651, 81))
        self.label_8.setPixmap(QPixmap(u"Dise\u00f1o sin t\u00edtulo.png"))
        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(280, 160, 61, 111))
        self.label_13.setLayoutDirection(Qt.RightToLeft)
        self.label_13.setTextFormat(Qt.AutoText)
        self.label_13.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.label_14 = QLabel(self.tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(-20, 160, 81, 111))
        self.label_14.setLayoutDirection(Qt.LeftToRight)
        self.label_14.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(350, 160, 81, 111))
        self.label_15.setLayoutDirection(Qt.LeftToRight)
        self.label_15.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.label_16 = QLabel(self.tab)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(650, 160, 61, 111))
        self.label_16.setLayoutDirection(Qt.RightToLeft)
        self.label_16.setTextFormat(Qt.AutoText)
        self.label_16.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.label_17 = QLabel(self.tab)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(170, 310, 81, 111))
        self.label_17.setLayoutDirection(Qt.LeftToRight)
        self.label_17.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.label_18 = QLabel(self.tab)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(470, 310, 61, 111))
        self.label_18.setLayoutDirection(Qt.RightToLeft)
        self.label_18.setTextFormat(Qt.AutoText)
        self.label_18.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.label_19 = QLabel(self.tab)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(320, 180, 71, 71))
        self.label_19.setPixmap(QPixmap(u"mas.png"))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.txt_a11 = QLineEdit(self.tab_2)
        self.txt_a11.setObjectName(u"txt_a11")
        self.txt_a11.setGeometry(QRect(150, 210, 51, 21))
        self.txt_a11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_a02 = QLineEdit(self.tab_2)
        self.txt_a02.setObjectName(u"txt_a02")
        self.txt_a02.setGeometry(QRect(220, 180, 51, 21))
        self.txt_a02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_b01 = QLineEdit(self.tab_2)
        self.txt_b01.setObjectName(u"txt_b01")
        self.txt_b01.setGeometry(QRect(510, 180, 51, 21))
        self.txt_b01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_ab00 = QLabel(self.tab_2)
        self.lbl_ab00.setObjectName(u"lbl_ab00")
        self.lbl_ab00.setGeometry(QRect(260, 330, 61, 16))
        self.lbl_ab00.setFont(font1)
        self.label_25 = QLabel(self.tab_2)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(280, 160, 61, 111))
        self.label_25.setLayoutDirection(Qt.RightToLeft)
        self.label_25.setTextFormat(Qt.AutoText)
        self.label_25.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_a00 = QLineEdit(self.tab_2)
        self.txt_a00.setObjectName(u"txt_a00")
        self.txt_a00.setGeometry(QRect(80, 180, 51, 21))
        self.txt_a00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_a22 = QLineEdit(self.tab_2)
        self.txt_a22.setObjectName(u"txt_a22")
        self.txt_a22.setGeometry(QRect(220, 240, 51, 21))
        self.txt_a22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_b20 = QLineEdit(self.tab_2)
        self.txt_b20.setObjectName(u"txt_b20")
        self.txt_b20.setGeometry(QRect(440, 240, 51, 21))
        self.txt_b20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(140, 130, 81, 31))
        self.label_12.setFont(font)
        self.label_24 = QLabel(self.tab_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(-20, 160, 81, 111))
        self.label_24.setLayoutDirection(Qt.LeftToRight)
        self.label_24.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.lbl_ab20 = QLabel(self.tab_2)
        self.lbl_ab20.setObjectName(u"lbl_ab20")
        self.lbl_ab20.setGeometry(QRect(260, 390, 61, 16))
        self.lbl_ab20.setFont(font1)
        self.txt_a01 = QLineEdit(self.tab_2)
        self.txt_a01.setObjectName(u"txt_a01")
        self.txt_a01.setGeometry(QRect(150, 180, 51, 21))
        self.txt_a01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_20 = QLabel(self.tab_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(350, 160, 81, 111))
        self.label_20.setLayoutDirection(Qt.LeftToRight)
        self.label_20.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(500, 130, 81, 31))
        self.label_9.setFont(font)
        self.lbl_ab12 = QLabel(self.tab_2)
        self.lbl_ab12.setObjectName(u"lbl_ab12")
        self.lbl_ab12.setGeometry(QRect(400, 360, 61, 16))
        self.lbl_ab12.setFont(font1)
        self.label_23 = QLabel(self.tab_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(170, 310, 81, 111))
        self.label_23.setLayoutDirection(Qt.LeftToRight)
        self.label_23.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.lbl_ab10 = QLabel(self.tab_2)
        self.lbl_ab10.setObjectName(u"lbl_ab10")
        self.lbl_ab10.setGeometry(QRect(260, 360, 61, 16))
        self.lbl_ab10.setFont(font1)
        self.label_22 = QLabel(self.tab_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(650, 160, 61, 111))
        self.label_22.setLayoutDirection(Qt.RightToLeft)
        self.label_22.setTextFormat(Qt.AutoText)
        self.label_22.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.lbl_ab21 = QLabel(self.tab_2)
        self.lbl_ab21.setObjectName(u"lbl_ab21")
        self.lbl_ab21.setGeometry(QRect(330, 390, 61, 16))
        self.lbl_ab21.setFont(font1)
        self.txt_b02 = QLineEdit(self.tab_2)
        self.txt_b02.setObjectName(u"txt_b02")
        self.txt_b02.setGeometry(QRect(580, 180, 51, 21))
        self.txt_b02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_ab11 = QLabel(self.tab_2)
        self.lbl_ab11.setObjectName(u"lbl_ab11")
        self.lbl_ab11.setGeometry(QRect(330, 360, 61, 16))
        self.lbl_ab11.setFont(font1)
        self.lbl_ab02 = QLabel(self.tab_2)
        self.lbl_ab02.setObjectName(u"lbl_ab02")
        self.lbl_ab02.setGeometry(QRect(400, 330, 61, 16))
        self.lbl_ab02.setFont(font1)
        self.txt_b12 = QLineEdit(self.tab_2)
        self.txt_b12.setObjectName(u"txt_b12")
        self.txt_b12.setGeometry(QRect(580, 210, 51, 21))
        self.txt_b12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_b10 = QLineEdit(self.tab_2)
        self.txt_b10.setObjectName(u"txt_b10")
        self.txt_b10.setGeometry(QRect(440, 210, 51, 21))
        self.txt_b10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_ab01 = QLabel(self.tab_2)
        self.lbl_ab01.setObjectName(u"lbl_ab01")
        self.lbl_ab01.setGeometry(QRect(330, 330, 61, 16))
        self.lbl_ab01.setFont(font1)
        self.txt_b21 = QLineEdit(self.tab_2)
        self.txt_b21.setObjectName(u"txt_b21")
        self.txt_b21.setGeometry(QRect(510, 240, 51, 21))
        self.txt_b21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_ab22 = QLabel(self.tab_2)
        self.lbl_ab22.setObjectName(u"lbl_ab22")
        self.lbl_ab22.setGeometry(QRect(400, 390, 61, 16))
        self.lbl_ab22.setFont(font1)
        self.txt_a21 = QLineEdit(self.tab_2)
        self.txt_a21.setObjectName(u"txt_a21")
        self.txt_a21.setGeometry(QRect(150, 240, 51, 21))
        self.txt_a21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_a20 = QLineEdit(self.tab_2)
        self.txt_a20.setObjectName(u"txt_a20")
        self.txt_a20.setGeometry(QRect(80, 240, 51, 21))
        self.txt_a20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_21 = QLabel(self.tab_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(320, 180, 71, 71))
        self.label_21.setPixmap(QPixmap(u"signo-menos-de-una-linea-en-posicion-horizontal.png"))
        self.txt_a10 = QLineEdit(self.tab_2)
        self.txt_a10.setObjectName(u"txt_a10")
        self.txt_a10.setGeometry(QRect(80, 210, 51, 21))
        self.txt_a10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_b11 = QLineEdit(self.tab_2)
        self.txt_b11.setObjectName(u"txt_b11")
        self.txt_b11.setGeometry(QRect(510, 210, 51, 21))
        self.txt_b11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_10 = QLabel(self.tab_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(320, 290, 81, 31))
        self.label_10.setFont(font)
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 20, 651, 81))
        self.label_11.setPixmap(QPixmap(u"Suma de Matrices.png"))
        self.label_26 = QLabel(self.tab_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(470, 310, 61, 111))
        self.label_26.setLayoutDirection(Qt.RightToLeft)
        self.label_26.setTextFormat(Qt.AutoText)
        self.label_26.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_a12 = QLineEdit(self.tab_2)
        self.txt_a12.setObjectName(u"txt_a12")
        self.txt_a12.setGeometry(QRect(220, 210, 51, 21))
        self.txt_a12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_b00 = QLineEdit(self.tab_2)
        self.txt_b00.setObjectName(u"txt_b00")
        self.txt_b00.setGeometry(QRect(440, 180, 51, 21))
        self.txt_b00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_b22 = QLineEdit(self.tab_2)
        self.txt_b22.setObjectName(u"txt_b22")
        self.txt_b22.setGeometry(QRect(580, 240, 51, 21))
        self.txt_b22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.btn_Restar = QPushButton(self.tab_2)
        self.btn_Restar.setObjectName(u"btn_Restar")
        self.btn_Restar.setGeometry(QRect(510, 420, 91, 41))
        self.btn_Restar.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.btn_limpiar2 = QPushButton(self.tab_2)
        self.btn_limpiar2.setObjectName(u"btn_limpiar2")
        self.btn_limpiar2.setGeometry(QRect(610, 420, 91, 41))
        self.btn_limpiar2.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);;")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.txt_ma02 = QLineEdit(self.tab_3)
        self.txt_ma02.setObjectName(u"txt_ma02")
        self.txt_ma02.setGeometry(QRect(220, 180, 51, 21))
        self.txt_ma02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_mb01 = QLineEdit(self.tab_3)
        self.txt_mb01.setObjectName(u"txt_mb01")
        self.txt_mb01.setGeometry(QRect(510, 180, 51, 21))
        self.txt_mb01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_abm00 = QLabel(self.tab_3)
        self.lbl_abm00.setObjectName(u"lbl_abm00")
        self.lbl_abm00.setGeometry(QRect(260, 330, 61, 16))
        self.lbl_abm00.setFont(font1)
        self.txt_ma00 = QLineEdit(self.tab_3)
        self.txt_ma00.setObjectName(u"txt_ma00")
        self.txt_ma00.setGeometry(QRect(80, 180, 51, 21))
        self.txt_ma00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_27 = QLabel(self.tab_3)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(280, 160, 61, 111))
        self.label_27.setLayoutDirection(Qt.RightToLeft)
        self.label_27.setTextFormat(Qt.AutoText)
        self.label_27.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_ma22 = QLineEdit(self.tab_3)
        self.txt_ma22.setObjectName(u"txt_ma22")
        self.txt_ma22.setGeometry(QRect(220, 240, 51, 21))
        self.txt_ma22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_mb20 = QLineEdit(self.tab_3)
        self.txt_mb20.setObjectName(u"txt_mb20")
        self.txt_mb20.setGeometry(QRect(440, 240, 51, 21))
        self.txt_mb20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_28 = QLabel(self.tab_3)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(140, 130, 81, 31))
        self.label_28.setFont(font)
        self.label_29 = QLabel(self.tab_3)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(-20, 160, 81, 111))
        self.label_29.setLayoutDirection(Qt.LeftToRight)
        self.label_29.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.lbl_abm20 = QLabel(self.tab_3)
        self.lbl_abm20.setObjectName(u"lbl_abm20")
        self.lbl_abm20.setGeometry(QRect(260, 390, 61, 16))
        self.lbl_abm20.setFont(font1)
        self.txt_ma01 = QLineEdit(self.tab_3)
        self.txt_ma01.setObjectName(u"txt_ma01")
        self.txt_ma01.setGeometry(QRect(150, 180, 51, 21))
        self.txt_ma01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_30 = QLabel(self.tab_3)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(350, 160, 81, 111))
        self.label_30.setLayoutDirection(Qt.LeftToRight)
        self.label_30.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.label_31 = QLabel(self.tab_3)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(500, 130, 81, 31))
        self.label_31.setFont(font)
        self.lbl_abm12 = QLabel(self.tab_3)
        self.lbl_abm12.setObjectName(u"lbl_abm12")
        self.lbl_abm12.setGeometry(QRect(400, 360, 61, 16))
        self.lbl_abm12.setFont(font1)
        self.label_32 = QLabel(self.tab_3)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(170, 310, 81, 111))
        self.label_32.setLayoutDirection(Qt.LeftToRight)
        self.label_32.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.lbl_abm10 = QLabel(self.tab_3)
        self.lbl_abm10.setObjectName(u"lbl_abm10")
        self.lbl_abm10.setGeometry(QRect(260, 360, 61, 16))
        self.lbl_abm10.setFont(font1)
        self.label_33 = QLabel(self.tab_3)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(650, 160, 61, 111))
        self.label_33.setLayoutDirection(Qt.RightToLeft)
        self.label_33.setTextFormat(Qt.AutoText)
        self.label_33.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.lbl_abm21 = QLabel(self.tab_3)
        self.lbl_abm21.setObjectName(u"lbl_abm21")
        self.lbl_abm21.setGeometry(QRect(330, 390, 61, 16))
        self.lbl_abm21.setFont(font1)
        self.txt_mb02 = QLineEdit(self.tab_3)
        self.txt_mb02.setObjectName(u"txt_mb02")
        self.txt_mb02.setGeometry(QRect(580, 180, 51, 21))
        self.txt_mb02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_abm11 = QLabel(self.tab_3)
        self.lbl_abm11.setObjectName(u"lbl_abm11")
        self.lbl_abm11.setGeometry(QRect(330, 360, 61, 16))
        self.lbl_abm11.setFont(font1)
        self.txt_mb12 = QLineEdit(self.tab_3)
        self.txt_mb12.setObjectName(u"txt_mb12")
        self.txt_mb12.setGeometry(QRect(580, 210, 51, 21))
        self.txt_mb12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_abm02 = QLabel(self.tab_3)
        self.lbl_abm02.setObjectName(u"lbl_abm02")
        self.lbl_abm02.setGeometry(QRect(400, 330, 61, 16))
        self.lbl_abm02.setFont(font1)
        self.txt_mb10 = QLineEdit(self.tab_3)
        self.txt_mb10.setObjectName(u"txt_mb10")
        self.txt_mb10.setGeometry(QRect(440, 210, 51, 21))
        self.txt_mb10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_abm01 = QLabel(self.tab_3)
        self.lbl_abm01.setObjectName(u"lbl_abm01")
        self.lbl_abm01.setGeometry(QRect(330, 330, 61, 16))
        self.lbl_abm01.setFont(font1)
        self.txt_mb21 = QLineEdit(self.tab_3)
        self.txt_mb21.setObjectName(u"txt_mb21")
        self.txt_mb21.setGeometry(QRect(510, 240, 51, 21))
        self.txt_mb21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_abm22 = QLabel(self.tab_3)
        self.lbl_abm22.setObjectName(u"lbl_abm22")
        self.lbl_abm22.setGeometry(QRect(400, 390, 61, 16))
        self.lbl_abm22.setFont(font1)
        self.txt_ma21 = QLineEdit(self.tab_3)
        self.txt_ma21.setObjectName(u"txt_ma21")
        self.txt_ma21.setGeometry(QRect(150, 240, 51, 21))
        self.txt_ma21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_ma20 = QLineEdit(self.tab_3)
        self.txt_ma20.setObjectName(u"txt_ma20")
        self.txt_ma20.setGeometry(QRect(80, 240, 51, 21))
        self.txt_ma20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_34 = QLabel(self.tab_3)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(320, 180, 71, 71))
        self.label_34.setPixmap(QPixmap(u"simbolo-de-multiplicacion.png"))
        self.txt_ma10 = QLineEdit(self.tab_3)
        self.txt_ma10.setObjectName(u"txt_ma10")
        self.txt_ma10.setGeometry(QRect(80, 210, 51, 21))
        self.txt_ma10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_mb11 = QLineEdit(self.tab_3)
        self.txt_mb11.setObjectName(u"txt_mb11")
        self.txt_mb11.setGeometry(QRect(510, 210, 51, 21))
        self.txt_mb11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_35 = QLabel(self.tab_3)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(320, 290, 81, 31))
        self.label_35.setFont(font)
        self.txt_mb00 = QLineEdit(self.tab_3)
        self.txt_mb00.setObjectName(u"txt_mb00")
        self.txt_mb00.setGeometry(QRect(440, 180, 51, 21))
        self.txt_mb00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_ma12 = QLineEdit(self.tab_3)
        self.txt_ma12.setObjectName(u"txt_ma12")
        self.txt_ma12.setGeometry(QRect(220, 210, 51, 21))
        self.txt_ma12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_mb22 = QLineEdit(self.tab_3)
        self.txt_mb22.setObjectName(u"txt_mb22")
        self.txt_mb22.setGeometry(QRect(580, 240, 51, 21))
        self.txt_mb22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_37 = QLabel(self.tab_3)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(470, 310, 61, 111))
        self.label_37.setLayoutDirection(Qt.RightToLeft)
        self.label_37.setTextFormat(Qt.AutoText)
        self.label_37.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_ma11 = QLineEdit(self.tab_3)
        self.txt_ma11.setObjectName(u"txt_ma11")
        self.txt_ma11.setGeometry(QRect(150, 210, 51, 21))
        self.txt_ma11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.btn_Multiplicar = QPushButton(self.tab_3)
        self.btn_Multiplicar.setObjectName(u"btn_Multiplicar")
        self.btn_Multiplicar.setGeometry(QRect(510, 420, 91, 41))
        self.btn_Multiplicar.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.btn_limpiar3 = QPushButton(self.tab_3)
        self.btn_limpiar3.setObjectName(u"btn_limpiar3")
        self.btn_limpiar3.setGeometry(QRect(610, 420, 91, 41))
        self.btn_limpiar3.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_65 = QLabel(self.tab_3)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(20, 20, 651, 81))
        self.label_65.setPixmap(QPixmap(u"Suma de Matrices (1).png"))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.label_38 = QLabel(self.tab_4)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(-30, 160, 81, 111))
        self.label_38.setLayoutDirection(Qt.LeftToRight)
        self.label_38.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.txt_ta12 = QLineEdit(self.tab_4)
        self.txt_ta12.setObjectName(u"txt_ta12")
        self.txt_ta12.setGeometry(QRect(210, 210, 51, 21))
        self.txt_ta12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_ta21 = QLineEdit(self.tab_4)
        self.txt_ta21.setObjectName(u"txt_ta21")
        self.txt_ta21.setGeometry(QRect(140, 240, 51, 21))
        self.txt_ta21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_ta02 = QLineEdit(self.tab_4)
        self.txt_ta02.setObjectName(u"txt_ta02")
        self.txt_ta02.setGeometry(QRect(210, 180, 51, 21))
        self.txt_ta02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_ta20 = QLineEdit(self.tab_4)
        self.txt_ta20.setObjectName(u"txt_ta20")
        self.txt_ta20.setGeometry(QRect(70, 240, 51, 21))
        self.txt_ta20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_39 = QLabel(self.tab_4)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(130, 130, 81, 31))
        self.label_39.setFont(font)
        self.label_40 = QLabel(self.tab_4)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(270, 160, 61, 111))
        self.label_40.setLayoutDirection(Qt.RightToLeft)
        self.label_40.setTextFormat(Qt.AutoText)
        self.label_40.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_ta10 = QLineEdit(self.tab_4)
        self.txt_ta10.setObjectName(u"txt_ta10")
        self.txt_ta10.setGeometry(QRect(70, 210, 51, 21))
        self.txt_ta10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_ta11 = QLineEdit(self.tab_4)
        self.txt_ta11.setObjectName(u"txt_ta11")
        self.txt_ta11.setGeometry(QRect(140, 210, 51, 21))
        self.txt_ta11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_ta00 = QLineEdit(self.tab_4)
        self.txt_ta00.setObjectName(u"txt_ta00")
        self.txt_ta00.setGeometry(QRect(70, 180, 51, 21))
        self.txt_ta00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_ta01 = QLineEdit(self.tab_4)
        self.txt_ta01.setObjectName(u"txt_ta01")
        self.txt_ta01.setGeometry(QRect(140, 180, 51, 21))
        self.txt_ta01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_ta22 = QLineEdit(self.tab_4)
        self.txt_ta22.setObjectName(u"txt_ta22")
        self.txt_ta22.setGeometry(QRect(210, 240, 51, 21))
        self.txt_ta22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_41 = QLabel(self.tab_4)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(18, 20, 651, 81))
        self.label_41.setPixmap(QPixmap(u"transpuesta.png"))
        self.btn_Transpuesta = QPushButton(self.tab_4)
        self.btn_Transpuesta.setObjectName(u"btn_Transpuesta")
        self.btn_Transpuesta.setGeometry(QRect(510, 420, 91, 41))
        self.btn_Transpuesta.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.btn_limpiar3_2 = QPushButton(self.tab_4)
        self.btn_limpiar3_2.setObjectName(u"btn_limpiar3_2")
        self.btn_limpiar3_2.setGeometry(QRect(610, 420, 91, 41))
        self.btn_limpiar3_2.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_at10 = QLabel(self.tab_4)
        self.lbl_at10.setObjectName(u"lbl_at10")
        self.lbl_at10.setGeometry(QRect(430, 210, 61, 16))
        self.lbl_at10.setFont(font1)
        self.lbl_at20 = QLabel(self.tab_4)
        self.lbl_at20.setObjectName(u"lbl_at20")
        self.lbl_at20.setGeometry(QRect(430, 240, 61, 16))
        self.lbl_at20.setFont(font1)
        self.lbl_at21 = QLabel(self.tab_4)
        self.lbl_at21.setObjectName(u"lbl_at21")
        self.lbl_at21.setGeometry(QRect(500, 240, 61, 16))
        self.lbl_at21.setFont(font1)
        self.label_42 = QLabel(self.tab_4)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(490, 140, 91, 31))
        self.label_42.setFont(font)
        self.lbl_at00 = QLabel(self.tab_4)
        self.lbl_at00.setObjectName(u"lbl_at00")
        self.lbl_at00.setGeometry(QRect(430, 180, 61, 16))
        self.lbl_at00.setFont(font1)
        self.lbl_at22 = QLabel(self.tab_4)
        self.lbl_at22.setObjectName(u"lbl_at22")
        self.lbl_at22.setGeometry(QRect(570, 240, 61, 16))
        self.lbl_at22.setFont(font1)
        self.lbl_at12 = QLabel(self.tab_4)
        self.lbl_at12.setObjectName(u"lbl_at12")
        self.lbl_at12.setGeometry(QRect(570, 210, 61, 16))
        self.lbl_at12.setFont(font1)
        self.lbl_at01 = QLabel(self.tab_4)
        self.lbl_at01.setObjectName(u"lbl_at01")
        self.lbl_at01.setGeometry(QRect(500, 180, 61, 16))
        self.lbl_at01.setFont(font1)
        self.lbl_at02 = QLabel(self.tab_4)
        self.lbl_at02.setObjectName(u"lbl_at02")
        self.lbl_at02.setGeometry(QRect(570, 180, 61, 16))
        self.lbl_at02.setFont(font1)
        self.label_43 = QLabel(self.tab_4)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(340, 160, 81, 111))
        self.label_43.setLayoutDirection(Qt.LeftToRight)
        self.label_43.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.lbl_at11 = QLabel(self.tab_4)
        self.lbl_at11.setObjectName(u"lbl_at11")
        self.lbl_at11.setGeometry(QRect(500, 210, 61, 16))
        self.lbl_at11.setFont(font1)
        self.label_44 = QLabel(self.tab_4)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(640, 160, 61, 111))
        self.label_44.setLayoutDirection(Qt.RightToLeft)
        self.label_44.setTextFormat(Qt.AutoText)
        self.label_44.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_45 = QLabel(self.tab_5)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(140, 160, 81, 111))
        self.label_45.setLayoutDirection(Qt.LeftToRight)
        self.label_45.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.txt_da20 = QLineEdit(self.tab_5)
        self.txt_da20.setObjectName(u"txt_da20")
        self.txt_da20.setGeometry(QRect(240, 240, 51, 21))
        self.txt_da20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_da10 = QLineEdit(self.tab_5)
        self.txt_da10.setObjectName(u"txt_da10")
        self.txt_da10.setGeometry(QRect(240, 210, 51, 21))
        self.txt_da10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_da21 = QLineEdit(self.tab_5)
        self.txt_da21.setObjectName(u"txt_da21")
        self.txt_da21.setGeometry(QRect(310, 240, 51, 21))
        self.txt_da21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_da12 = QLineEdit(self.tab_5)
        self.txt_da12.setObjectName(u"txt_da12")
        self.txt_da12.setGeometry(QRect(380, 210, 51, 21))
        self.txt_da12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_46 = QLabel(self.tab_5)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(300, 130, 81, 31))
        self.label_46.setFont(font)
        self.txt_da00 = QLineEdit(self.tab_5)
        self.txt_da00.setObjectName(u"txt_da00")
        self.txt_da00.setGeometry(QRect(240, 180, 51, 21))
        self.txt_da00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.btn_Determinante = QPushButton(self.tab_5)
        self.btn_Determinante.setObjectName(u"btn_Determinante")
        self.btn_Determinante.setGeometry(QRect(510, 420, 91, 41))
        self.btn_Determinante.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_da01 = QLineEdit(self.tab_5)
        self.txt_da01.setObjectName(u"txt_da01")
        self.txt_da01.setGeometry(QRect(310, 180, 51, 21))
        self.txt_da01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_47 = QLabel(self.tab_5)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(440, 160, 61, 111))
        self.label_47.setLayoutDirection(Qt.RightToLeft)
        self.label_47.setTextFormat(Qt.AutoText)
        self.label_47.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_da22 = QLineEdit(self.tab_5)
        self.txt_da22.setObjectName(u"txt_da22")
        self.txt_da22.setGeometry(QRect(380, 240, 51, 21))
        self.txt_da22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_48 = QLabel(self.tab_5)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(18, 20, 651, 81))
        self.label_48.setPixmap(QPixmap(u"Suma de Matrices (2).png"))
        self.txt_da02 = QLineEdit(self.tab_5)
        self.txt_da02.setObjectName(u"txt_da02")
        self.txt_da02.setGeometry(QRect(380, 180, 51, 21))
        self.txt_da02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_da11 = QLineEdit(self.tab_5)
        self.txt_da11.setObjectName(u"txt_da11")
        self.txt_da11.setGeometry(QRect(310, 210, 51, 21))
        self.txt_da11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.btn_limpiar3_3 = QPushButton(self.tab_5)
        self.btn_limpiar3_3.setObjectName(u"btn_limpiar3_3")
        self.btn_limpiar3_3.setGeometry(QRect(610, 420, 91, 41))
        self.btn_limpiar3_3.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_49 = QLabel(self.tab_5)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(290, 310, 111, 31))
        self.label_49.setFont(font)
        self.label_50 = QLabel(self.tab_5)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(290, 350, 41, 31))
        self.label_50.setFont(font)
        self.lbl_determinante = QLabel(self.tab_5)
        self.lbl_determinante.setObjectName(u"lbl_determinante")
        self.lbl_determinante.setGeometry(QRect(340, 360, 61, 16))
        self.lbl_determinante.setFont(font1)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.label_57 = QLabel(self.tab_6)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(640, 160, 61, 111))
        self.label_57.setLayoutDirection(Qt.RightToLeft)
        self.label_57.setTextFormat(Qt.AutoText)
        self.label_57.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_Ma22 = QLineEdit(self.tab_6)
        self.txt_Ma22.setObjectName(u"txt_Ma22")
        self.txt_Ma22.setGeometry(QRect(210, 240, 51, 21))
        self.txt_Ma22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_adj01 = QLabel(self.tab_6)
        self.lbl_adj01.setObjectName(u"lbl_adj01")
        self.lbl_adj01.setGeometry(QRect(500, 180, 61, 16))
        self.lbl_adj01.setFont(font1)
        self.lbl_adj12 = QLabel(self.tab_6)
        self.lbl_adj12.setObjectName(u"lbl_adj12")
        self.lbl_adj12.setGeometry(QRect(570, 210, 61, 16))
        self.lbl_adj12.setFont(font1)
        self.lbl_adj00 = QLabel(self.tab_6)
        self.lbl_adj00.setObjectName(u"lbl_adj00")
        self.lbl_adj00.setGeometry(QRect(430, 180, 61, 16))
        self.lbl_adj00.setFont(font1)
        self.txt_Ma21 = QLineEdit(self.tab_6)
        self.txt_Ma21.setObjectName(u"txt_Ma21")
        self.txt_Ma21.setGeometry(QRect(140, 240, 51, 21))
        self.txt_Ma21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_Ma11 = QLineEdit(self.tab_6)
        self.txt_Ma11.setObjectName(u"txt_Ma11")
        self.txt_Ma11.setGeometry(QRect(140, 210, 51, 21))
        self.txt_Ma11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_adj11 = QLabel(self.tab_6)
        self.lbl_adj11.setObjectName(u"lbl_adj11")
        self.lbl_adj11.setGeometry(QRect(500, 210, 61, 16))
        self.lbl_adj11.setFont(font1)
        self.label_56 = QLabel(self.tab_6)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(18, 20, 651, 81))
        self.label_56.setPixmap(QPixmap(u"Suma de Matrices (4).png"))
        self.lbl_adj20 = QLabel(self.tab_6)
        self.lbl_adj20.setObjectName(u"lbl_adj20")
        self.lbl_adj20.setGeometry(QRect(430, 240, 61, 16))
        self.lbl_adj20.setFont(font1)
        self.txt_Ma02 = QLineEdit(self.tab_6)
        self.txt_Ma02.setObjectName(u"txt_Ma02")
        self.txt_Ma02.setGeometry(QRect(210, 180, 51, 21))
        self.txt_Ma02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_Ma20 = QLineEdit(self.tab_6)
        self.txt_Ma20.setObjectName(u"txt_Ma20")
        self.txt_Ma20.setGeometry(QRect(70, 240, 51, 21))
        self.txt_Ma20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_Ma01 = QLineEdit(self.tab_6)
        self.txt_Ma01.setObjectName(u"txt_Ma01")
        self.txt_Ma01.setGeometry(QRect(140, 180, 51, 21))
        self.txt_Ma01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_55 = QLabel(self.tab_6)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(340, 160, 81, 111))
        self.label_55.setLayoutDirection(Qt.LeftToRight)
        self.label_55.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.btn_limpiar3_4 = QPushButton(self.tab_6)
        self.btn_limpiar3_4.setObjectName(u"btn_limpiar3_4")
        self.btn_limpiar3_4.setGeometry(QRect(610, 420, 91, 41))
        self.btn_limpiar3_4.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_adj22 = QLabel(self.tab_6)
        self.lbl_adj22.setObjectName(u"lbl_adj22")
        self.lbl_adj22.setGeometry(QRect(570, 240, 61, 16))
        self.lbl_adj22.setFont(font1)
        self.label_51 = QLabel(self.tab_6)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(490, 140, 91, 31))
        self.label_51.setFont(font)
        self.label_52 = QLabel(self.tab_6)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(130, 130, 81, 31))
        self.label_52.setFont(font)
        self.lbl_adj02 = QLabel(self.tab_6)
        self.lbl_adj02.setObjectName(u"lbl_adj02")
        self.lbl_adj02.setGeometry(QRect(570, 180, 61, 16))
        self.lbl_adj02.setFont(font1)
        self.txt_Ma00 = QLineEdit(self.tab_6)
        self.txt_Ma00.setObjectName(u"txt_Ma00")
        self.txt_Ma00.setGeometry(QRect(70, 180, 51, 21))
        self.txt_Ma00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_53 = QLabel(self.tab_6)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(270, 160, 61, 111))
        self.label_53.setLayoutDirection(Qt.RightToLeft)
        self.label_53.setTextFormat(Qt.AutoText)
        self.label_53.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_Ma10 = QLineEdit(self.tab_6)
        self.txt_Ma10.setObjectName(u"txt_Ma10")
        self.txt_Ma10.setGeometry(QRect(70, 210, 51, 21))
        self.txt_Ma10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_adj10 = QLabel(self.tab_6)
        self.lbl_adj10.setObjectName(u"lbl_adj10")
        self.lbl_adj10.setGeometry(QRect(430, 210, 61, 16))
        self.lbl_adj10.setFont(font1)
        self.label_54 = QLabel(self.tab_6)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(-30, 160, 81, 111))
        self.label_54.setLayoutDirection(Qt.LeftToRight)
        self.label_54.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.lbl_adj21 = QLabel(self.tab_6)
        self.lbl_adj21.setObjectName(u"lbl_adj21")
        self.lbl_adj21.setGeometry(QRect(500, 240, 61, 16))
        self.lbl_adj21.setFont(font1)
        self.btn_Adjunta = QPushButton(self.tab_6)
        self.btn_Adjunta.setObjectName(u"btn_Adjunta")
        self.btn_Adjunta.setGeometry(QRect(510, 420, 91, 41))
        self.btn_Adjunta.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_Ma12 = QLineEdit(self.tab_6)
        self.txt_Ma12.setObjectName(u"txt_Ma12")
        self.txt_Ma12.setGeometry(QRect(210, 210, 51, 21))
        self.txt_Ma12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.txt_Ia22 = QLineEdit(self.tab_7)
        self.txt_Ia22.setObjectName(u"txt_Ia22")
        self.txt_Ia22.setGeometry(QRect(210, 240, 51, 21))
        self.txt_Ia22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_inv01 = QLabel(self.tab_7)
        self.lbl_inv01.setObjectName(u"lbl_inv01")
        self.lbl_inv01.setGeometry(QRect(500, 180, 61, 16))
        self.lbl_inv01.setFont(font1)
        self.lbl_inv12 = QLabel(self.tab_7)
        self.lbl_inv12.setObjectName(u"lbl_inv12")
        self.lbl_inv12.setGeometry(QRect(570, 210, 61, 16))
        self.lbl_inv12.setFont(font1)
        self.lbl_inv00 = QLabel(self.tab_7)
        self.lbl_inv00.setObjectName(u"lbl_inv00")
        self.lbl_inv00.setGeometry(QRect(430, 180, 61, 16))
        self.lbl_inv00.setFont(font1)
        self.txt_Ia21 = QLineEdit(self.tab_7)
        self.txt_Ia21.setObjectName(u"txt_Ia21")
        self.txt_Ia21.setGeometry(QRect(140, 240, 51, 21))
        self.txt_Ia21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_Ia11 = QLineEdit(self.tab_7)
        self.txt_Ia11.setObjectName(u"txt_Ia11")
        self.txt_Ia11.setGeometry(QRect(140, 210, 51, 21))
        self.txt_Ia11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_inv11 = QLabel(self.tab_7)
        self.lbl_inv11.setObjectName(u"lbl_inv11")
        self.lbl_inv11.setGeometry(QRect(500, 210, 61, 16))
        self.lbl_inv11.setFont(font1)
        self.label_58 = QLabel(self.tab_7)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(18, 20, 651, 81))
        self.label_58.setPixmap(QPixmap(u"Suma de Matrices (3).png"))
        self.label_59 = QLabel(self.tab_7)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(640, 160, 61, 111))
        self.label_59.setLayoutDirection(Qt.RightToLeft)
        self.label_59.setTextFormat(Qt.AutoText)
        self.label_59.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_Ia02 = QLineEdit(self.tab_7)
        self.txt_Ia02.setObjectName(u"txt_Ia02")
        self.txt_Ia02.setGeometry(QRect(210, 180, 51, 21))
        self.txt_Ia02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_inv20 = QLabel(self.tab_7)
        self.lbl_inv20.setObjectName(u"lbl_inv20")
        self.lbl_inv20.setGeometry(QRect(430, 240, 61, 16))
        self.lbl_inv20.setFont(font1)
        self.txt_Ia20 = QLineEdit(self.tab_7)
        self.txt_Ia20.setObjectName(u"txt_Ia20")
        self.txt_Ia20.setGeometry(QRect(70, 240, 51, 21))
        self.txt_Ia20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_Ia01 = QLineEdit(self.tab_7)
        self.txt_Ia01.setObjectName(u"txt_Ia01")
        self.txt_Ia01.setGeometry(QRect(140, 180, 51, 21))
        self.txt_Ia01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_60 = QLabel(self.tab_7)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(340, 160, 81, 111))
        self.label_60.setLayoutDirection(Qt.LeftToRight)
        self.label_60.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.btn_limpiar3_5 = QPushButton(self.tab_7)
        self.btn_limpiar3_5.setObjectName(u"btn_limpiar3_5")
        self.btn_limpiar3_5.setGeometry(QRect(610, 420, 91, 41))
        self.btn_limpiar3_5.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_inv22 = QLabel(self.tab_7)
        self.lbl_inv22.setObjectName(u"lbl_inv22")
        self.lbl_inv22.setGeometry(QRect(570, 240, 61, 16))
        self.lbl_inv22.setFont(font1)
        self.label_61 = QLabel(self.tab_7)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(490, 140, 91, 31))
        self.label_61.setFont(font)
        self.label_62 = QLabel(self.tab_7)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(130, 130, 81, 31))
        self.label_62.setFont(font)
        self.lbl_inv02 = QLabel(self.tab_7)
        self.lbl_inv02.setObjectName(u"lbl_inv02")
        self.lbl_inv02.setGeometry(QRect(570, 180, 61, 16))
        self.lbl_inv02.setFont(font1)
        self.txt_Ia00 = QLineEdit(self.tab_7)
        self.txt_Ia00.setObjectName(u"txt_Ia00")
        self.txt_Ia00.setGeometry(QRect(70, 180, 51, 21))
        self.txt_Ia00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_63 = QLabel(self.tab_7)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(270, 160, 61, 111))
        self.label_63.setLayoutDirection(Qt.RightToLeft)
        self.label_63.setTextFormat(Qt.AutoText)
        self.label_63.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_Ia10 = QLineEdit(self.tab_7)
        self.txt_Ia10.setObjectName(u"txt_Ia10")
        self.txt_Ia10.setGeometry(QRect(70, 210, 51, 21))
        self.txt_Ia10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_inv10 = QLabel(self.tab_7)
        self.lbl_inv10.setObjectName(u"lbl_inv10")
        self.lbl_inv10.setGeometry(QRect(430, 210, 61, 16))
        self.lbl_inv10.setFont(font1)
        self.label_64 = QLabel(self.tab_7)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(-30, 160, 81, 111))
        self.label_64.setLayoutDirection(Qt.LeftToRight)
        self.label_64.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.lbl_inv21 = QLabel(self.tab_7)
        self.lbl_inv21.setObjectName(u"lbl_inv21")
        self.lbl_inv21.setGeometry(QRect(500, 240, 61, 16))
        self.lbl_inv21.setFont(font1)
        self.btn_Inversa = QPushButton(self.tab_7)
        self.btn_Inversa.setObjectName(u"btn_Inversa")
        self.btn_Inversa.setGeometry(QRect(510, 420, 91, 41))
        self.btn_Inversa.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_Ia12 = QLineEdit(self.tab_7)
        self.txt_Ia12.setObjectName(u"txt_Ia12")
        self.txt_Ia12.setGeometry(QRect(210, 210, 51, 21))
        self.txt_Ia12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.label_66 = QLabel(self.tab_8)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(18, 20, 651, 81))
        self.label_66.setPixmap(QPixmap(u"METODO ADJUNTO.png"))
        self.btn_MetodoAdj = QPushButton(self.tab_8)
        self.btn_MetodoAdj.setObjectName(u"btn_MetodoAdj")
        self.btn_MetodoAdj.setGeometry(QRect(510, 420, 91, 41))
        self.btn_MetodoAdj.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.btn_limpiar3_6 = QPushButton(self.tab_8)
        self.btn_limpiar3_6.setObjectName(u"btn_limpiar3_6")
        self.btn_limpiar3_6.setGeometry(QRect(610, 420, 91, 41))
        self.btn_limpiar3_6.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_EcAdj00 = QLineEdit(self.tab_8)
        self.txt_EcAdj00.setObjectName(u"txt_EcAdj00")
        self.txt_EcAdj00.setGeometry(QRect(190, 170, 51, 21))
        self.txt_EcAdj00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_EcAdj10 = QLineEdit(self.tab_8)
        self.txt_EcAdj10.setObjectName(u"txt_EcAdj10")
        self.txt_EcAdj10.setGeometry(QRect(190, 200, 51, 21))
        self.txt_EcAdj10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_EcAdj22 = QLineEdit(self.tab_8)
        self.txt_EcAdj22.setObjectName(u"txt_EcAdj22")
        self.txt_EcAdj22.setGeometry(QRect(370, 230, 51, 21))
        self.txt_EcAdj22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_EcAdj02 = QLineEdit(self.tab_8)
        self.txt_EcAdj02.setObjectName(u"txt_EcAdj02")
        self.txt_EcAdj02.setGeometry(QRect(370, 170, 51, 21))
        self.txt_EcAdj02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_EcAdj12 = QLineEdit(self.tab_8)
        self.txt_EcAdj12.setObjectName(u"txt_EcAdj12")
        self.txt_EcAdj12.setGeometry(QRect(370, 200, 51, 21))
        self.txt_EcAdj12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_EcAdj20 = QLineEdit(self.tab_8)
        self.txt_EcAdj20.setObjectName(u"txt_EcAdj20")
        self.txt_EcAdj20.setGeometry(QRect(190, 230, 51, 21))
        self.txt_EcAdj20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_72 = QLabel(self.tab_8)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setGeometry(QRect(100, 150, 81, 111))
        self.label_72.setLayoutDirection(Qt.LeftToRight)
        self.label_72.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.txt_EcAdj21 = QLineEdit(self.tab_8)
        self.txt_EcAdj21.setObjectName(u"txt_EcAdj21")
        self.txt_EcAdj21.setGeometry(QRect(280, 230, 51, 21))
        self.txt_EcAdj21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_73 = QLabel(self.tab_8)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setGeometry(QRect(320, 120, 81, 31))
        self.label_73.setFont(font)
        self.label_74 = QLabel(self.tab_8)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setGeometry(QRect(530, 150, 61, 111))
        self.label_74.setLayoutDirection(Qt.RightToLeft)
        self.label_74.setTextFormat(Qt.AutoText)
        self.label_74.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_EcAdj11 = QLineEdit(self.tab_8)
        self.txt_EcAdj11.setObjectName(u"txt_EcAdj11")
        self.txt_EcAdj11.setGeometry(QRect(280, 200, 51, 21))
        self.txt_EcAdj11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_EcAdj01 = QLineEdit(self.tab_8)
        self.txt_EcAdj01.setObjectName(u"txt_EcAdj01")
        self.txt_EcAdj01.setGeometry(QRect(280, 170, 51, 21))
        self.txt_EcAdj01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_75 = QLabel(self.tab_8)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setGeometry(QRect(250, 230, 21, 21))
        self.label_75.setFont(font)
        self.label_76 = QLabel(self.tab_8)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setGeometry(QRect(250, 200, 21, 21))
        self.label_76.setFont(font)
        self.label_77 = QLabel(self.tab_8)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setGeometry(QRect(250, 170, 21, 21))
        self.label_77.setFont(font)
        self.label_78 = QLabel(self.tab_8)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setGeometry(QRect(340, 170, 21, 21))
        self.label_78.setFont(font)
        self.label_79 = QLabel(self.tab_8)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setGeometry(QRect(340, 200, 21, 21))
        self.label_79.setFont(font)
        self.label_80 = QLabel(self.tab_8)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setGeometry(QRect(340, 230, 21, 21))
        self.label_80.setFont(font)
        self.label_81 = QLabel(self.tab_8)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setGeometry(QRect(430, 170, 21, 21))
        self.label_81.setFont(font)
        self.label_82 = QLabel(self.tab_8)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setGeometry(QRect(430, 200, 21, 21))
        self.label_82.setFont(font)
        self.label_83 = QLabel(self.tab_8)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setGeometry(QRect(430, 230, 21, 21))
        self.label_83.setFont(font)
        self.label_84 = QLabel(self.tab_8)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setGeometry(QRect(460, 170, 21, 21))
        self.label_84.setFont(font)
        self.label_85 = QLabel(self.tab_8)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setGeometry(QRect(460, 200, 21, 21))
        self.label_85.setFont(font)
        self.label_86 = QLabel(self.tab_8)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setGeometry(QRect(460, 230, 21, 21))
        self.label_86.setFont(font)
        self.txt_EcMb10 = QLineEdit(self.tab_8)
        self.txt_EcMb10.setObjectName(u"txt_EcMb10")
        self.txt_EcMb10.setGeometry(QRect(480, 200, 51, 21))
        self.txt_EcMb10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_EcMb20 = QLineEdit(self.tab_8)
        self.txt_EcMb20.setObjectName(u"txt_EcMb20")
        self.txt_EcMb20.setGeometry(QRect(480, 230, 51, 21))
        self.txt_EcMb20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_EcMb00 = QLineEdit(self.tab_8)
        self.txt_EcMb00.setObjectName(u"txt_EcMb00")
        self.txt_EcMb00.setGeometry(QRect(480, 170, 51, 21))
        self.txt_EcMb00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_87 = QLabel(self.tab_8)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setGeometry(QRect(390, 340, 21, 21))
        self.label_87.setFont(font)
        self.label_88 = QLabel(self.tab_8)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setGeometry(QRect(390, 400, 21, 21))
        self.label_88.setFont(font)
        self.label_89 = QLabel(self.tab_8)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setGeometry(QRect(390, 370, 21, 21))
        self.label_89.setFont(font)
        self.label_90 = QLabel(self.tab_8)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setGeometry(QRect(240, 320, 81, 111))
        self.label_90.setLayoutDirection(Qt.LeftToRight)
        self.label_90.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.label_91 = QLabel(self.tab_8)
        self.label_91.setObjectName(u"label_91")
        self.label_91.setGeometry(QRect(400, 320, 61, 111))
        self.label_91.setLayoutDirection(Qt.RightToLeft)
        self.label_91.setTextFormat(Qt.AutoText)
        self.label_91.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.lbl_Mc20 = QLabel(self.tab_8)
        self.lbl_Mc20.setObjectName(u"lbl_Mc20")
        self.lbl_Mc20.setGeometry(QRect(320, 400, 61, 16))
        self.lbl_Mc20.setFont(font1)
        self.lbl_Mc00 = QLabel(self.tab_8)
        self.lbl_Mc00.setObjectName(u"lbl_Mc00")
        self.lbl_Mc00.setGeometry(QRect(320, 340, 61, 16))
        self.lbl_Mc00.setFont(font1)
        self.lbl_Mc10 = QLabel(self.tab_8)
        self.lbl_Mc10.setObjectName(u"lbl_Mc10")
        self.lbl_Mc10.setGeometry(QRect(320, 370, 61, 16))
        self.lbl_Mc10.setFont(font1)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.label_67 = QLabel(self.tab_9)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setGeometry(QRect(18, 20, 651, 81))
        self.label_67.setPixmap(QPixmap(u"METDO CRAMER.png"))
        self.btn_MetodoCramer = QPushButton(self.tab_9)
        self.btn_MetodoCramer.setObjectName(u"btn_MetodoCramer")
        self.btn_MetodoCramer.setGeometry(QRect(510, 420, 91, 41))
        self.btn_MetodoCramer.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.btn_limpiar3_7 = QPushButton(self.tab_9)
        self.btn_limpiar3_7.setObjectName(u"btn_limpiar3_7")
        self.btn_limpiar3_7.setGeometry(QRect(610, 420, 91, 41))
        self.btn_limpiar3_7.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_rCramer10 = QLabel(self.tab_9)
        self.lbl_rCramer10.setObjectName(u"lbl_rCramer10")
        self.lbl_rCramer10.setGeometry(QRect(320, 370, 61, 16))
        self.lbl_rCramer10.setFont(font1)
        self.label_92 = QLabel(self.tab_9)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setGeometry(QRect(430, 200, 21, 21))
        self.label_92.setFont(font)
        self.txt_EcS20 = QLineEdit(self.tab_9)
        self.txt_EcS20.setObjectName(u"txt_EcS20")
        self.txt_EcS20.setGeometry(QRect(190, 230, 51, 21))
        self.txt_EcS20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_93 = QLabel(self.tab_9)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setGeometry(QRect(460, 230, 21, 21))
        self.label_93.setFont(font)
        self.txt_EcS10 = QLineEdit(self.tab_9)
        self.txt_EcS10.setObjectName(u"txt_EcS10")
        self.txt_EcS10.setGeometry(QRect(190, 200, 51, 21))
        self.txt_EcS10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_EcS12 = QLineEdit(self.tab_9)
        self.txt_EcS12.setObjectName(u"txt_EcS12")
        self.txt_EcS12.setGeometry(QRect(370, 200, 51, 21))
        self.txt_EcS12.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.txt_EcC00 = QLineEdit(self.tab_9)
        self.txt_EcC00.setObjectName(u"txt_EcC00")
        self.txt_EcC00.setGeometry(QRect(480, 170, 51, 21))
        self.txt_EcC00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.lbl_rCramer00 = QLabel(self.tab_9)
        self.lbl_rCramer00.setObjectName(u"lbl_rCramer00")
        self.lbl_rCramer00.setGeometry(QRect(320, 340, 61, 16))
        self.lbl_rCramer00.setFont(font1)
        self.label_94 = QLabel(self.tab_9)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setGeometry(QRect(340, 200, 21, 21))
        self.label_94.setFont(font)
        self.label_95 = QLabel(self.tab_9)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setGeometry(QRect(460, 200, 21, 21))
        self.label_95.setFont(font)
        self.label_96 = QLabel(self.tab_9)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setGeometry(QRect(250, 200, 21, 21))
        self.label_96.setFont(font)
        self.txt_EcC20 = QLineEdit(self.tab_9)
        self.txt_EcC20.setObjectName(u"txt_EcC20")
        self.txt_EcC20.setGeometry(QRect(480, 230, 51, 21))
        self.txt_EcC20.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_97 = QLabel(self.tab_9)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setGeometry(QRect(240, 320, 81, 111))
        self.label_97.setLayoutDirection(Qt.LeftToRight)
        self.label_97.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.txt_EcC10 = QLineEdit(self.tab_9)
        self.txt_EcC10.setObjectName(u"txt_EcC10")
        self.txt_EcC10.setGeometry(QRect(480, 200, 51, 21))
        self.txt_EcC10.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_98 = QLabel(self.tab_9)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setGeometry(QRect(250, 170, 21, 21))
        self.label_98.setFont(font)
        self.lbl_rCramer20 = QLabel(self.tab_9)
        self.lbl_rCramer20.setObjectName(u"lbl_rCramer20")
        self.lbl_rCramer20.setGeometry(QRect(320, 400, 61, 16))
        self.lbl_rCramer20.setFont(font1)
        self.label_99 = QLabel(self.tab_9)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setGeometry(QRect(390, 370, 21, 21))
        self.label_99.setFont(font)
        self.label_100 = QLabel(self.tab_9)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setGeometry(QRect(100, 150, 81, 111))
        self.label_100.setLayoutDirection(Qt.LeftToRight)
        self.label_100.setPixmap(QPixmap(u"cerrar-parentesi.png"))
        self.txt_EcS01 = QLineEdit(self.tab_9)
        self.txt_EcS01.setObjectName(u"txt_EcS01")
        self.txt_EcS01.setGeometry(QRect(280, 170, 51, 21))
        self.txt_EcS01.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_101 = QLabel(self.tab_9)
        self.label_101.setObjectName(u"label_101")
        self.label_101.setGeometry(QRect(320, 120, 81, 31))
        self.label_101.setFont(font)
        self.label_102 = QLabel(self.tab_9)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setGeometry(QRect(250, 230, 21, 21))
        self.label_102.setFont(font)
        self.label_103 = QLabel(self.tab_9)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setGeometry(QRect(460, 170, 21, 21))
        self.label_103.setFont(font)
        self.label_104 = QLabel(self.tab_9)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setGeometry(QRect(430, 230, 21, 21))
        self.label_104.setFont(font)
        self.txt_EcS00 = QLineEdit(self.tab_9)
        self.txt_EcS00.setObjectName(u"txt_EcS00")
        self.txt_EcS00.setGeometry(QRect(190, 170, 51, 21))
        self.txt_EcS00.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_105 = QLabel(self.tab_9)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setGeometry(QRect(530, 150, 61, 111))
        self.label_105.setLayoutDirection(Qt.RightToLeft)
        self.label_105.setTextFormat(Qt.AutoText)
        self.label_105.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.label_106 = QLabel(self.tab_9)
        self.label_106.setObjectName(u"label_106")
        self.label_106.setGeometry(QRect(390, 340, 21, 21))
        self.label_106.setFont(font)
        self.txt_EcS21 = QLineEdit(self.tab_9)
        self.txt_EcS21.setObjectName(u"txt_EcS21")
        self.txt_EcS21.setGeometry(QRect(280, 230, 51, 21))
        self.txt_EcS21.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_107 = QLabel(self.tab_9)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setGeometry(QRect(340, 230, 21, 21))
        self.label_107.setFont(font)
        self.label_108 = QLabel(self.tab_9)
        self.label_108.setObjectName(u"label_108")
        self.label_108.setGeometry(QRect(340, 170, 21, 21))
        self.label_108.setFont(font)
        self.txt_EcS02 = QLineEdit(self.tab_9)
        self.txt_EcS02.setObjectName(u"txt_EcS02")
        self.txt_EcS02.setGeometry(QRect(370, 170, 51, 21))
        self.txt_EcS02.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_109 = QLabel(self.tab_9)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setGeometry(QRect(390, 400, 21, 21))
        self.label_109.setFont(font)
        self.txt_EcS22 = QLineEdit(self.tab_9)
        self.txt_EcS22.setObjectName(u"txt_EcS22")
        self.txt_EcS22.setGeometry(QRect(370, 230, 51, 21))
        self.txt_EcS22.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_110 = QLabel(self.tab_9)
        self.label_110.setObjectName(u"label_110")
        self.label_110.setGeometry(QRect(400, 320, 61, 111))
        self.label_110.setLayoutDirection(Qt.RightToLeft)
        self.label_110.setTextFormat(Qt.AutoText)
        self.label_110.setPixmap(QPixmap(u"cerrar-parentesis.png"))
        self.txt_EcS11 = QLineEdit(self.tab_9)
        self.txt_EcS11.setObjectName(u"txt_EcS11")
        self.txt_EcS11.setGeometry(QRect(280, 200, 51, 21))
        self.txt_EcS11.setStyleSheet(u"background-color: rgb(255, 232, 115);\n"
"color: rgb(0, 0, 0);")
        self.label_111 = QLabel(self.tab_9)
        self.label_111.setObjectName(u"label_111")
        self.label_111.setGeometry(QRect(430, 170, 21, 21))
        self.label_111.setFont(font)
        self.tabWidget.addTab(self.tab_9, "")
        self.label = QLabel(Dialog)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(100, 10, 501, 81))
        self.label.setPixmap(QPixmap(u"Operaciones de matrices.png"))
        self.label_3 = QLabel(Dialog)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(610, 0, 111, 91))
        self.label_3.setPixmap(QPixmap(u"logo2.png"))
        self.label_2 = QLabel(Dialog)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(-30, 10, 111, 81))
        self.label_2.setPixmap(QPixmap(u"logo.png"))
        self.label_4 = QLabel(Dialog)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 100, 261, 61))
        self.label_4.setPixmap(QPixmap(u"Con esta calculadora podr\u00e1s calcular un determinante, un rango, una suma de matrices, un producto de matrices, una matriz inversa y otros..png"))

        self.retranslateUi(Dialog)
        self.btn_Limpiar.clicked.connect(self.txt_A00.clear)
        self.btn_Limpiar.clicked.connect(self.txt_A10.clear)
        self.btn_Limpiar.clicked.connect(self.txt_A20.clear)
        self.btn_Limpiar.clicked.connect(self.txt_A01.clear)
        self.btn_Limpiar.clicked.connect(self.txt_A11.clear)
        self.btn_Limpiar.clicked.connect(self.txt_A21.clear)
        self.btn_Limpiar.clicked.connect(self.txt_A02.clear)
        self.btn_Limpiar.clicked.connect(self.txt_A12.clear)
        self.btn_Limpiar.clicked.connect(self.txt_A22.clear)
        self.btn_Limpiar.clicked.connect(self.txt_B02.clear)
        self.btn_Limpiar.clicked.connect(self.txt_B12.clear)
        self.btn_Limpiar.clicked.connect(self.txt_B22.clear)
        self.btn_Limpiar.clicked.connect(self.txt_B00.clear)
        self.btn_Limpiar.clicked.connect(self.txt_B10.clear)
        self.btn_Limpiar.clicked.connect(self.txt_B20.clear)
        self.btn_Limpiar.clicked.connect(self.txt_B01.clear)
        self.btn_Limpiar.clicked.connect(self.txt_B11.clear)
        self.btn_Limpiar.clicked.connect(self.txt_B21.clear)
        self.btn_Limpiar.clicked.connect(self.lbl_AB00.clear)
        self.btn_Limpiar.clicked.connect(self.lbl_AB10.clear)
        self.btn_Limpiar.clicked.connect(self.lbl_AB20.clear)
        self.btn_Limpiar.clicked.connect(self.lbl_AB01.clear)
        self.btn_Limpiar.clicked.connect(self.lbl_AB11.clear)
        self.btn_Limpiar.clicked.connect(self.lbl_AB21.clear)
        self.btn_Limpiar.clicked.connect(self.lbl_AB02.clear)
        self.btn_Limpiar.clicked.connect(self.lbl_AB12.clear)
        self.btn_Limpiar.clicked.connect(self.lbl_AB22.clear)
        self.btn_limpiar2.clicked.connect(self.txt_a00.clear)
        self.btn_limpiar2.clicked.connect(self.txt_a10.clear)
        self.btn_limpiar2.clicked.connect(self.txt_a20.clear)
        self.btn_limpiar2.clicked.connect(self.txt_a01.clear)
        self.btn_limpiar2.clicked.connect(self.txt_a11.clear)
        self.btn_limpiar2.clicked.connect(self.txt_a21.clear)
        self.btn_limpiar2.clicked.connect(self.txt_a02.clear)
        self.btn_limpiar2.clicked.connect(self.txt_a12.clear)
        self.btn_limpiar2.clicked.connect(self.txt_a22.clear)
        self.btn_limpiar2.clicked.connect(self.lbl_ab00.clear)
        self.btn_limpiar2.clicked.connect(self.lbl_ab10.clear)
        self.btn_limpiar2.clicked.connect(self.lbl_ab20.clear)
        self.btn_limpiar2.clicked.connect(self.lbl_ab01.clear)
        self.btn_limpiar2.clicked.connect(self.lbl_ab11.clear)
        self.btn_limpiar2.clicked.connect(self.lbl_ab21.clear)
        self.btn_limpiar2.clicked.connect(self.lbl_ab02.clear)
        self.btn_limpiar2.clicked.connect(self.lbl_ab12.clear)
        self.btn_limpiar2.clicked.connect(self.lbl_ab22.clear)
        self.btn_limpiar2.clicked.connect(self.txt_b00.clear)
        self.btn_limpiar2.clicked.connect(self.txt_b01.clear)
        self.btn_limpiar2.clicked.connect(self.txt_b02.clear)
        self.btn_limpiar2.clicked.connect(self.txt_b10.clear)
        self.btn_limpiar2.clicked.connect(self.txt_b11.clear)
        self.btn_limpiar2.clicked.connect(self.txt_b12.clear)
        self.btn_limpiar2.clicked.connect(self.txt_b20.clear)
        self.btn_limpiar2.clicked.connect(self.txt_b21.clear)
        self.btn_limpiar2.clicked.connect(self.txt_b22.clear)
        self.btn_limpiar3.clicked.connect(self.txt_ma00.clear)
        self.btn_limpiar3.clicked.connect(self.txt_ma10.clear)
        self.btn_limpiar3.clicked.connect(self.txt_ma20.clear)
        self.btn_limpiar3.clicked.connect(self.txt_ma01.clear)
        self.btn_limpiar3.clicked.connect(self.txt_ma11.clear)
        self.btn_limpiar3.clicked.connect(self.txt_ma21.clear)
        self.btn_limpiar3.clicked.connect(self.txt_ma02.clear)
        self.btn_limpiar3.clicked.connect(self.txt_ma12.clear)
        self.btn_limpiar3.clicked.connect(self.txt_ma22.clear)
        self.btn_limpiar3.clicked.connect(self.lbl_abm00.clear)
        self.btn_limpiar3.clicked.connect(self.lbl_abm10.clear)
        self.btn_limpiar3.clicked.connect(self.lbl_abm20.clear)
        self.btn_limpiar3.clicked.connect(self.lbl_abm01.clear)
        self.btn_limpiar3.clicked.connect(self.lbl_abm11.clear)
        self.btn_limpiar3.clicked.connect(self.lbl_abm21.clear)
        self.btn_limpiar3.clicked.connect(self.lbl_abm02.clear)
        self.btn_limpiar3.clicked.connect(self.lbl_abm12.clear)
        self.btn_limpiar3.clicked.connect(self.lbl_abm22.clear)
        self.btn_limpiar3.clicked.connect(self.txt_mb00.clear)
        self.btn_limpiar3.clicked.connect(self.txt_mb01.clear)
        self.btn_limpiar3.clicked.connect(self.txt_mb02.clear)
        self.btn_limpiar3.clicked.connect(self.txt_mb10.clear)
        self.btn_limpiar3.clicked.connect(self.txt_mb11.clear)
        self.btn_limpiar3.clicked.connect(self.txt_mb12.clear)
        self.btn_limpiar3.clicked.connect(self.txt_mb20.clear)
        self.btn_limpiar3.clicked.connect(self.txt_mb21.clear)
        self.btn_limpiar3.clicked.connect(self.txt_mb22.clear)
        self.btn_limpiar3_2.clicked.connect(self.txt_ta00.clear)
        self.btn_limpiar3_2.clicked.connect(self.txt_ta10.clear)
        self.btn_limpiar3_2.clicked.connect(self.txt_ta20.clear)
        self.btn_limpiar3_2.clicked.connect(self.txt_ta01.clear)
        self.btn_limpiar3_2.clicked.connect(self.txt_ta11.clear)
        self.btn_limpiar3_2.clicked.connect(self.txt_ta21.clear)
        self.btn_limpiar3_2.clicked.connect(self.txt_ta02.clear)
        self.btn_limpiar3_2.clicked.connect(self.txt_ta12.clear)
        self.btn_limpiar3_2.clicked.connect(self.txt_ta22.clear)
        self.btn_limpiar3_2.clicked.connect(self.lbl_at00.clear)
        self.btn_limpiar3_2.clicked.connect(self.lbl_at10.clear)
        self.btn_limpiar3_2.clicked.connect(self.lbl_at20.clear)
        self.btn_limpiar3_2.clicked.connect(self.lbl_at01.clear)
        self.btn_limpiar3_2.clicked.connect(self.lbl_at11.clear)
        self.btn_limpiar3_2.clicked.connect(self.lbl_at21.clear)
        self.btn_limpiar3_2.clicked.connect(self.lbl_at02.clear)
        self.btn_limpiar3_2.clicked.connect(self.lbl_at12.clear)
        self.btn_limpiar3_2.clicked.connect(self.lbl_at22.clear)
        self.btn_limpiar3_3.clicked.connect(self.txt_da00.clear)
        self.btn_limpiar3_3.clicked.connect(self.txt_da10.clear)
        self.btn_limpiar3_3.clicked.connect(self.txt_da20.clear)
        self.btn_limpiar3_3.clicked.connect(self.txt_da01.clear)
        self.btn_limpiar3_3.clicked.connect(self.txt_da11.clear)
        self.btn_limpiar3_3.clicked.connect(self.txt_da21.clear)
        self.btn_limpiar3_3.clicked.connect(self.txt_da02.clear)
        self.btn_limpiar3_3.clicked.connect(self.txt_da12.clear)
        self.btn_limpiar3_3.clicked.connect(self.txt_da22.clear)
        self.btn_limpiar3_4.clicked.connect(self.txt_Ma00.clear)
        self.btn_limpiar3_4.clicked.connect(self.txt_Ma10.clear)
        self.btn_limpiar3_4.clicked.connect(self.txt_Ma20.clear)
        self.btn_limpiar3_4.clicked.connect(self.txt_Ma01.clear)
        self.btn_limpiar3_4.clicked.connect(self.txt_Ma11.clear)
        self.btn_limpiar3_4.clicked.connect(self.txt_Ma21.clear)
        self.btn_limpiar3_4.clicked.connect(self.txt_Ma02.clear)
        self.btn_limpiar3_4.clicked.connect(self.txt_Ma12.clear)
        self.btn_limpiar3_4.clicked.connect(self.txt_Ma22.clear)
        self.btn_limpiar3_4.clicked.connect(self.lbl_adj00.clear)
        self.btn_limpiar3_4.clicked.connect(self.lbl_adj10.clear)
        self.btn_limpiar3_4.clicked.connect(self.lbl_adj20.clear)
        self.btn_limpiar3_4.clicked.connect(self.lbl_adj01.clear)
        self.btn_limpiar3_4.clicked.connect(self.lbl_adj11.clear)
        self.btn_limpiar3_4.clicked.connect(self.lbl_adj21.clear)
        self.btn_limpiar3_4.clicked.connect(self.lbl_adj02.clear)
        self.btn_limpiar3_4.clicked.connect(self.lbl_adj12.clear)
        self.btn_limpiar3_4.clicked.connect(self.lbl_adj22.clear)
        self.btn_limpiar3_5.clicked.connect(self.txt_Ia00.clear)
        self.btn_limpiar3_5.clicked.connect(self.txt_Ia10.clear)
        self.btn_limpiar3_5.clicked.connect(self.txt_Ia20.clear)
        self.btn_limpiar3_5.clicked.connect(self.txt_Ia01.clear)
        self.btn_limpiar3_5.clicked.connect(self.txt_Ia11.clear)
        self.btn_limpiar3_5.clicked.connect(self.txt_Ia21.clear)
        self.btn_limpiar3_5.clicked.connect(self.txt_Ia02.clear)
        self.btn_limpiar3_5.clicked.connect(self.txt_Ia12.clear)
        self.btn_limpiar3_5.clicked.connect(self.txt_Ia22.clear)
        self.btn_limpiar3_5.clicked.connect(self.lbl_inv00.clear)
        self.btn_limpiar3_5.clicked.connect(self.lbl_inv10.clear)
        self.btn_limpiar3_5.clicked.connect(self.lbl_inv20.clear)
        self.btn_limpiar3_5.clicked.connect(self.lbl_inv01.clear)
        self.btn_limpiar3_5.clicked.connect(self.lbl_inv11.clear)
        self.btn_limpiar3_5.clicked.connect(self.lbl_inv21.clear)
        self.btn_limpiar3_5.clicked.connect(self.lbl_inv02.clear)
        self.btn_limpiar3_5.clicked.connect(self.lbl_inv12.clear)
        self.btn_limpiar3_5.clicked.connect(self.lbl_inv22.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcAdj00.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcAdj10.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcAdj20.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcAdj01.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcAdj11.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcAdj21.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcAdj02.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcAdj12.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcAdj22.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcMb00.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcMb10.clear)
        self.btn_limpiar3_6.clicked.connect(self.txt_EcMb20.clear)
        self.btn_limpiar3_6.clicked.connect(self.lbl_Mc00.clear)
        self.btn_limpiar3_6.clicked.connect(self.lbl_Mc10.clear)
        self.btn_limpiar3_6.clicked.connect(self.lbl_Mc20.clear)
        self.btn_limpiar3_7.clicked.connect(self.lbl_rCramer00.clear)
        self.btn_limpiar3_7.clicked.connect(self.lbl_rCramer10.clear)
        self.btn_limpiar3_7.clicked.connect(self.lbl_rCramer20.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcC00.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcC10.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcC20.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcS00.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcS10.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcS20.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcS01.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcS11.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcS21.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcS02.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcS12.clear)
        self.btn_limpiar3_7.clicked.connect(self.txt_EcS22.clear)

        self.tabWidget.setCurrentIndex(8)


        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.btn_Limpiar.setText(QCoreApplication.translate("Dialog", u"Limpiar", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"Matriz A ", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"Matriz B", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Matriz AB ", None))
        self.lbl_AB00.setText("")
        self.lbl_AB01.setText("")
        self.lbl_AB02.setText("")
        self.lbl_AB10.setText("")
        self.lbl_AB11.setText("")
        self.lbl_AB12.setText("")
        self.lbl_AB20.setText("")
        self.lbl_AB21.setText("")
        self.lbl_AB22.setText("")
        self.btn_Sumar.setText(QCoreApplication.translate("Dialog", u"Sumar", None))
        self.label_8.setText("")
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_15.setText("")
        self.label_16.setText("")
        self.label_17.setText("")
        self.label_18.setText("")
        self.label_19.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Dialog", u"Suma", None))
        self.lbl_ab00.setText("")
        self.label_25.setText("")
        self.label_12.setText(QCoreApplication.translate("Dialog", u"Matriz A ", None))
        self.label_24.setText("")
        self.lbl_ab20.setText("")
        self.label_20.setText("")
        self.label_9.setText(QCoreApplication.translate("Dialog", u"Matriz B", None))
        self.lbl_ab12.setText("")
        self.label_23.setText("")
        self.lbl_ab10.setText("")
        self.label_22.setText("")
        self.lbl_ab21.setText("")
        self.lbl_ab11.setText("")
        self.lbl_ab02.setText("")
        self.lbl_ab01.setText("")
        self.lbl_ab22.setText("")
        self.label_21.setText("")
        self.label_10.setText(QCoreApplication.translate("Dialog", u"Matriz AB ", None))
        self.label_11.setText("")
        self.label_26.setText("")
        self.btn_Restar.setText(QCoreApplication.translate("Dialog", u"Restar", None))
        self.btn_limpiar2.setText(QCoreApplication.translate("Dialog", u"Limpiar", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Dialog", u"Resta", None))
        self.lbl_abm00.setText("")
        self.label_27.setText("")
        self.label_28.setText(QCoreApplication.translate("Dialog", u"Matriz A ", None))
        self.label_29.setText("")
        self.lbl_abm20.setText("")
        self.label_30.setText("")
        self.label_31.setText(QCoreApplication.translate("Dialog", u"Matriz B", None))
        self.lbl_abm12.setText("")
        self.label_32.setText("")
        self.lbl_abm10.setText("")
        self.label_33.setText("")
        self.lbl_abm21.setText("")
        self.lbl_abm11.setText("")
        self.lbl_abm02.setText("")
        self.lbl_abm01.setText("")
        self.lbl_abm22.setText("")
        self.label_34.setText("")
        self.label_35.setText(QCoreApplication.translate("Dialog", u"Matriz AB ", None))
        self.label_37.setText("")
        self.btn_Multiplicar.setText(QCoreApplication.translate("Dialog", u"Multiplicar", None))
        self.btn_limpiar3.setText(QCoreApplication.translate("Dialog", u"Limpiar", None))
        self.label_65.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Dialog", u"Multiplicacion", None))
        self.label_38.setText("")
        self.label_39.setText(QCoreApplication.translate("Dialog", u"Matriz A ", None))
        self.label_40.setText("")
        self.label_41.setText("")
        self.btn_Transpuesta.setText(QCoreApplication.translate("Dialog", u"Calcular", None))
        self.btn_limpiar3_2.setText(QCoreApplication.translate("Dialog", u"Limpiar", None))
        self.lbl_at10.setText("")
        self.lbl_at20.setText("")
        self.lbl_at21.setText("")
        self.label_42.setText(QCoreApplication.translate("Dialog", u"Matriz AT", None))
        self.lbl_at00.setText("")
        self.lbl_at22.setText("")
        self.lbl_at12.setText("")
        self.lbl_at01.setText("")
        self.lbl_at02.setText("")
        self.label_43.setText("")
        self.lbl_at11.setText("")
        self.label_44.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Dialog", u"Transpuesta", None))
        self.label_45.setText("")
        self.label_46.setText(QCoreApplication.translate("Dialog", u"Matriz A ", None))
        self.btn_Determinante.setText(QCoreApplication.translate("Dialog", u"Calcular", None))
        self.label_47.setText("")
        self.label_48.setText("")
        self.btn_limpiar3_3.setText(QCoreApplication.translate("Dialog", u"Limpiar", None))
        self.label_49.setText(QCoreApplication.translate("Dialog", u"|A| = DP - DS", None))
        self.label_50.setText(QCoreApplication.translate("Dialog", u"|A| =", None))
        self.lbl_determinante.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("Dialog", u"Determinante", None))
        self.label_57.setText("")
        self.lbl_adj01.setText("")
        self.lbl_adj12.setText("")
        self.lbl_adj00.setText("")
        self.lbl_adj11.setText("")
        self.label_56.setText("")
        self.lbl_adj20.setText("")
        self.label_55.setText("")
        self.btn_limpiar3_4.setText(QCoreApplication.translate("Dialog", u"Limpiar", None))
        self.lbl_adj22.setText("")
        self.label_51.setText(QCoreApplication.translate("Dialog", u"Matriz ADJ", None))
        self.label_52.setText(QCoreApplication.translate("Dialog", u"Matriz A ", None))
        self.lbl_adj02.setText("")
        self.label_53.setText("")
        self.lbl_adj10.setText("")
        self.label_54.setText("")
        self.lbl_adj21.setText("")
        self.btn_Adjunta.setText(QCoreApplication.translate("Dialog", u"Calcular", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("Dialog", u"Adjunta", None))
        self.lbl_inv01.setText("")
        self.lbl_inv12.setText("")
        self.lbl_inv00.setText("")
        self.lbl_inv11.setText("")
        self.label_58.setText("")
        self.label_59.setText("")
        self.lbl_inv20.setText("")
        self.label_60.setText("")
        self.btn_limpiar3_5.setText(QCoreApplication.translate("Dialog", u"Limpiar", None))
        self.lbl_inv22.setText("")
        self.label_61.setText(QCoreApplication.translate("Dialog", u"Matriz A-1", None))
        self.label_62.setText(QCoreApplication.translate("Dialog", u"Matriz A ", None))
        self.lbl_inv02.setText("")
        self.label_63.setText("")
        self.lbl_inv10.setText("")
        self.label_64.setText("")
        self.lbl_inv21.setText("")
        self.btn_Inversa.setText(QCoreApplication.translate("Dialog", u"Calcular", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("Dialog", u"Inversa", None))
        self.label_66.setText("")
        self.btn_MetodoAdj.setText(QCoreApplication.translate("Dialog", u"Calcular", None))
        self.btn_limpiar3_6.setText(QCoreApplication.translate("Dialog", u"Limpiar", None))
        self.label_72.setText("")
        self.label_73.setText(QCoreApplication.translate("Dialog", u"Matriz A ", None))
        self.label_74.setText("")
        self.label_75.setText(QCoreApplication.translate("Dialog", u"x", None))
        self.label_76.setText(QCoreApplication.translate("Dialog", u"x", None))
        self.label_77.setText(QCoreApplication.translate("Dialog", u"x", None))
        self.label_78.setText(QCoreApplication.translate("Dialog", u"y", None))
        self.label_79.setText(QCoreApplication.translate("Dialog", u"y", None))
        self.label_80.setText(QCoreApplication.translate("Dialog", u"y", None))
        self.label_81.setText(QCoreApplication.translate("Dialog", u"z", None))
        self.label_82.setText(QCoreApplication.translate("Dialog", u"z", None))
        self.label_83.setText(QCoreApplication.translate("Dialog", u"z", None))
        self.label_84.setText(QCoreApplication.translate("Dialog", u"=", None))
        self.label_85.setText(QCoreApplication.translate("Dialog", u"=", None))
        self.label_86.setText(QCoreApplication.translate("Dialog", u"=", None))
        self.label_87.setText(QCoreApplication.translate("Dialog", u"x", None))
        self.label_88.setText(QCoreApplication.translate("Dialog", u"z", None))
        self.label_89.setText(QCoreApplication.translate("Dialog", u"y", None))
        self.label_90.setText("")
        self.label_91.setText("")
        self.lbl_Mc20.setText("")
        self.lbl_Mc00.setText("")
        self.lbl_Mc10.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QCoreApplication.translate("Dialog", u"Metodo Adjunto", None))
        self.label_67.setText("")
        self.btn_MetodoCramer.setText(QCoreApplication.translate("Dialog", u"Calcular", None))
        self.btn_limpiar3_7.setText(QCoreApplication.translate("Dialog", u"Limpiar", None))
        self.lbl_rCramer10.setText("")
        self.label_92.setText(QCoreApplication.translate("Dialog", u"z", None))
        self.label_93.setText(QCoreApplication.translate("Dialog", u"=", None))
        self.lbl_rCramer00.setText("")
        self.label_94.setText(QCoreApplication.translate("Dialog", u"y", None))
        self.label_95.setText(QCoreApplication.translate("Dialog", u"=", None))
        self.label_96.setText(QCoreApplication.translate("Dialog", u"x", None))
        self.label_97.setText("")
        self.label_98.setText(QCoreApplication.translate("Dialog", u"x", None))
        self.lbl_rCramer20.setText("")
        self.label_99.setText(QCoreApplication.translate("Dialog", u"y", None))
        self.label_100.setText("")
        self.label_101.setText(QCoreApplication.translate("Dialog", u"Matriz A ", None))
        self.label_102.setText(QCoreApplication.translate("Dialog", u"x", None))
        self.label_103.setText(QCoreApplication.translate("Dialog", u"=", None))
        self.label_104.setText(QCoreApplication.translate("Dialog", u"z", None))
        self.label_105.setText("")
        self.label_106.setText(QCoreApplication.translate("Dialog", u"x", None))
        self.label_107.setText(QCoreApplication.translate("Dialog", u"y", None))
        self.label_108.setText(QCoreApplication.translate("Dialog", u"y", None))
        self.label_109.setText(QCoreApplication.translate("Dialog", u"z", None))
        self.label_110.setText("")
        self.label_111.setText(QCoreApplication.translate("Dialog", u"z", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QCoreApplication.translate("Dialog", u"Cramer", None))
        self.label.setText("")
        self.label_3.setText("")
        self.label_2.setText("")
        self.label_4.setText("")
    # retranslateUi




